package constants

const (
	BASE_HIT_CHANCE = 0.3
	RAND_HIT_CHANCE = 0.5

	DAMAGE_DISPERSION = 0.2

	BASE_CRIT_CHANCE        = 0.2
	CRIT_DAMAGE_COEFFICIENT = 1.5

	VAMPIRE_ABILITY_RATE = 0.1
	SNAKE_SLEEP_CHANCE   = 0.1
)
