package constants

const (
	BASE_COUNT_ITEM_IN_DUNGEON  = 15
	BASE_COUNT_ENEMY_IN_DUNGEON = 12

	MIN_FOOD_PERCENT = 30
	MAX_FOOD_PERCENT = 60

	MIN_ELIXIR_PERCENT = 20
	MAX_ELIXIR_PERCENT = 50

	MIN_SCROLL_PERCENT = 10
	MAX_SCROLL_PERCENT = 20

	MIN_WEAPON_STRENGTH = 20
	MAX_WEAPON_STRENGTH = 40

	BACKPACK_SIZE = 9

	EFFECT_BASE_TIME = 21

	LOW       = 1
	MEDIUM    = 2
	HIGH      = 3
	VERY_HIGH = 4

	BASE_ENEMY_HEALTH   = 50
	BASE_ENEMY_AGILITY  = 30
	BASE_ENEMY_STRENGTH = 15

	VARIABLE_ENEMY_HEALTH   = 10
	VARIABLE_ENEMY_AGILITY  = 5
	VARIABLE_ENEMY_STRENGTH = 5

	HERO_MAX_HEALTH = 500
	HERO_AGILITY    = 80
	HERO_STRENGTH   = 80
)
